import { PropertyProps } from "@/interfaces";

export const properties: PropertyProps[] = [
  {
    id: 1,
    name: "Modern City Apartment",
    address: { state: "Lagos", city: "Lekki", country: "Nigeria" },
    rating: 4.62,
    category: ["City View", "WiFi", "Self Check-in"],
    price: 2200,
    offers: { bed: "1", shower: "1", occupants: "2" },
    image: "https://example.com/image14.jpg",
    discount: "",
  },
  {
    id: 2,
    name: "Luxury Safari Lodge",
    address: { state: "Serengeti", city: "Mara", country: "Tanzania" },
    rating: 4.97,
    category: ["Safari", "Guided Tours", "Free Breakfast"],
    price: 4500,
    offers: { bed: "4", shower: "4", occupants: "6-8" },
    image: "https://example.com/image15.jpg",
    discount: "20",
  },
  {
    id: 3,
    name: "Countryside Cottage",
    address: { state: "Cotswolds", city: "Gloucestershire", country: "UK" },
    rating: 4.58,
    category: ["Countryside", "Fireplace", "Self Check-in"],
    price: 1800,
    offers: { bed: "2", shower: "1", occupants: "2-4" },
    image: "https://example.com/image16.jpg",
    discount: "25",
  },
  {
    id: 4,
    name: "Riverfront Mansion",
    address: { state: "Paris", city: "Île-de-France", country: "France" },
    rating: 4.86,
    category: ["Riverfront", "Private Garden", "Self Check-in"],
    price: 5000,
    offers: { bed: "4", shower: "3", occupants: "6-8" },
    image: "https://example.com/image17.jpg",
    discount: "30",
  },
  {
    id: 5,
    name: "Ski Chalet",
    address: { state: "Zermatt", city: "Valais", country: "Switzerland" },
    rating: 4.75,
    category: ["Mountain View", "Ski Access", "Fireplace"],
    price: 3900,
    offers: { bed: "3", shower: "3", occupants: "4-5" },
    image: "https://example.com/image18.jpg",
    discount: "",
  },
  {
    id: 6,
    name: "Island Paradise Villa",
    address: { state: "Mahe", city: "Victoria", country: "Seychelles" },
    rating: 4.98,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 6500,
    offers: { bed: "5", shower: "5", occupants: "8-10" },
    image: "https://example.com/image19.jpg",
    discount: "60",
  },
  {
    id: 7,
    name: "Clifftop Retreat",
    address: { state: "Cape Town", city: "Western Cape", country: "South Africa" },
    rating: 4.78,
    category: ["Ocean View", "Private Pool", "Self Check-in"],
    price: 4100,
    offers: { bed: "3", shower: "3", occupants: "4-5" },
    image: "https://example.com/image20.jpg",
    discount: "",
  },
];
